#IP 配置
#本机ip
host.ip=172.24.39.10
#tomcat config
spring.application.name=iot-center-accesstcp
server.port=18720
server.session-timeout=1800
server.tomcat.uri-encoding=utf-8
server.tomcat.max-threads=500
server.servlet.context-path=
server.servlet.path=/
server.tomcat.access-log-pattern=%t [%a] [%I] [%H-%m] %U %s %T
server.tomcat.access-log-enabled=true

#eureka config
eureka.instance.lease-renewal-interval-in-seconds =5
eureka.instance.lease-expiration-duration-in-seconds =15
eureka.client.serviceUrl.defaultZone=http://${host.ip}:18710/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

#redis config
spring.redis.database=0
spring.redis.host=${host.ip}
spring.redis.port=6379
spring.redis.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.redis.jedis.pool.max-idle=8
spring.redis.jedis.pool.max-wait=-1
spring.redis.jedis.pool.max-active=8
spring.redis.jedis.pool.min-idle=0
spring.redis.timeout=0
spring.servlet.multipart.max-file-size=1000Mb
spring.servlet.multipart.max-request-size=1000Mb
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false


#mybatis
mybatis.configuration.mapUnderscoreToCamelCase=true
mybatis.configuration.call-setters-on-nulls=true
#DB mysql configuration:
spring.datasource.accesstcp.driverClassName=com.mysql.jdbc.Driver
spring.datasource.accesstcp.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.accesstcp.url=jdbc:mysql://${host.ip}:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
spring.datasource.accesstcp.username=root
spring.datasource.accesstcp.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.datasource.accesstcp.publicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL19LiGbPzoLBZJvUqZoxeEeknRpuGc8aeMq9j+I/Jl79mem92wjn7NwrwmYfAziF6IaKZpDaIph64DdrfoesosCAwEAAQ==
spring.datasource.accesstcp.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${spring.datasource.accesstcp.publicKey}
spring.datasource.accesstcp.initialSize=5
spring.datasource.accesstcp.minIdle=5
spring.datasource.accesstcp.maxActive=20
spring.datasource.accesstcp.maxWait=60000
spring.datasource.accesstcp.timeBetweenEvictionRunsMillis=60000
spring.datasource.accesstcp.minEvictableIdleTimeMillis=300000
spring.datasource.accesstcp.validationQuery=SELECT 1 FROM DUAL
spring.datasource.accesstcp.testWhileIdle=true
spring.datasource.accesstcp.testOnBorrow=false
spring.datasource.accesstcp.testOnReturn=false
spring.datasource.accesstcp.filters=config,wall,log4j,stat
spring.datasource.accesstcp.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.accesstcp.useGlobalDataSourceStat=true
