#tomcat config
spring.application.name=iot-center-accesstcp
server.port=18720
server.session-timeout=1800
server.tomcat.uri-encoding=utf-8
server.tomcat.max-threads=500
server.servlet.context-path=
server.servlet.path=/
server.tomcat.access-log-pattern=%t [%a] [%I] [%H-%m] %U %s %T
server.tomcat.access-log-enabled=true
#注册中心
#Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
eureka.instance.lease-renewal-interval-in-seconds =5
#Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
eureka.instance.lease-expiration-duration-in-seconds =15
eureka.client.serviceUrl.defaultZone=http://172.24.39.108:18710/eureka/
#eureka.client.serviceUrl.defaultZone=http://10.45.156.192:18900/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
#server.tomcat.basedir=../tomcat
# Redis数据库索引（默认为0
spring.redis.database=0
# Redis服务器地址
#spring.redis.host=10.45.156.195
#spring.redis.host=redis-e72c595-dcs-redis5.dcs.huaweicloud.com
#spring.redis.host=10.45.152.33
spring.redis.host=172.24.39.108
#spring.redis.host=10.45.156.192
# 服务器连接端口
spring.redis.port=6379
# Redis服务器连接密码(默认为空)
spring.redis.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
#spring.redis.password=yjh@123!
# 连接池最大连接数（使用负值表示没有限制
spring.redis.jedis.pool.max-idle=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1
# 连接池中的最大空闲连接
spring.redis.jedis.pool.max-active=8
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=0
# 连接超时时间（毫秒）
spring.redis.timeout=0
spring.servlet.multipart.max-file-size=1000Mb
spring.servlet.multipart.max-request-size=1000Mb
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false


#mybatis 下划线自动转驼峰
mybatis.configuration.mapUnderscoreToCamelCase=true
mybatis.configuration.call-setters-on-nulls=true
#DB mysql configuration:
spring.datasource.accesstcp.driverClassName=com.mysql.jdbc.Driver
spring.datasource.accesstcp.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.accesstcp.url=jdbc:mysql://172.24.39.108:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
#spring.datasource.accessudp.url=jdbc:mysql://127.0.0.1:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
spring.datasource.accesstcp.username=root
spring.datasource.accesstcp.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.datasource.accesstcp.publicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL19LiGbPzoLBZJvUqZoxeEeknRpuGc8aeMq9j+I/Jl79mem92wjn7NwrwmYfAziF6IaKZpDaIph64DdrfoesosCAwEAAQ==
spring.datasource.accesstcp.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${spring.datasource.accesstcp.publicKey}
# 下面为连接池的补充设置，应用到上面所有数据源中
spring.datasource.accesstcp.initialSize=5
spring.datasource.accesstcp.minIdle=5
spring.datasource.accesstcp.maxActive=20
# 配置获取连接等待超时的时间
spring.datasource.accesstcp.maxWait=60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource.accesstcp.timeBetweenEvictionRunsMillis=60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource.accesstcp.minEvictableIdleTimeMillis=300000
spring.datasource.accesstcp.validationQuery=SELECT 1 FROM DUAL
spring.datasource.accesstcp.testWhileIdle=true
spring.datasource.accesstcp.testOnBorrow=false
spring.datasource.accesstcp.testOnReturn=false
# druid数据源监控web
spring.datasource.accesstcp.filters=config,wall,log4j,stat
spring.datasource.accesstcp.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.accesstcp.useGlobalDataSourceStat=true
#fegin调用
#请求处理的超时时间
ribbon.ReadTimeout=60000
#请求连接的超时时间
ribbon.ConnectTimeout=60000
#过滤掉的属性
attr.id=15,17,16,31,25,26,107,108,188
#netty 上报的ip
a.interface.flag = 1
netty.server.port=10011
netty.server.url=127.0.0.1
netty.server.ftps.ip=192.168.33.19
netty.server.ftps.port=10012
netty.server.ftps.username=ftpuser
netty.server.ftps.password=ttasdqwe123
netty.server.ftps.keypw=1
#thread pool config
thread.corePoolSize=100
thread.maxPoolSize=300
thread.queueCapacity=80
thread.keepAliveTime=60

#quartz配置
spring.quartz.auto-startup=true
spring.quartz.job-store-type=jdbc
spring.quartz.schedulerName=TcpScheduler
spring.quartz.properties.org.quartz.scheduler.instanceName=TcpSchedulerInstance
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=true
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval=5000
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=60000
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount=25
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
spring.quartz.properties.org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true

# 上级系统唯一标识
spring.union.upSystem=Server01
spring.union.cruiseHost=Client02
spring.union.stationCode=123

#可靠性统计上报时间
spring.device.time=0 0 10 * * ?
#spring.device.time=0/30 * * * * ?
