spring.application.name=voice-imitator
server.port=52001
server.servlet.context-path=/

spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

spring.mvc.async.request-timeout=20000
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

voice.ret-error=true
voice.voice-path=voice
voice.file-url-path=http://172.24.39.9/voice-files/