#IP 配置
#本机ip
host.ip=172.24.39.9
#tomcat config
spring.application.name=iot-center-accessudp
server.port=18714
server.session-timeout=1800
server.tomcat.uri-encoding=utf-8
server.tomcat.max-threads=500
server.servlet.context-path=
server.servlet.path=/
server.tomcat.access-log-pattern=%t [%a] [%I] [%H-%m] %U %s %T
server.tomcat.access-log-enabled=true

eureka.instance.lease-renewal-interval-in-seconds =5
eureka.instance.lease-expiration-duration-in-seconds =15
eureka.client.serviceUrl.defaultZone=http://${host.ip}:18710/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

spring.redis.database=0
spring.redis.host=${host.ip}
spring.redis.port=6379
spring.redis.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.redis.jedis.pool.max-idle=8
spring.redis.jedis.pool.max-wait=-1
spring.redis.jedis.pool.max-active=8
spring.redis.jedis.pool.min-idle=0
spring.redis.timeout=0
spring.servlet.multipart.max-file-size=1000Mb
spring.servlet.multipart.max-request-size=1000Mb
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

#mybatis
mybatis.configuration.mapUnderscoreToCamelCase=true
#DB mysql configuration:
spring.datasource.accessudp.driverClassName=com.mysql.jdbc.Driver
spring.datasource.accessudp.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.accessudp.url=jdbc:mysql://${host.ip}:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
spring.datasource.accessudp.username=root
spring.datasource.accessudp.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.datasource.accessudp.publicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL19LiGbPzoLBZJvUqZoxeEeknRpuGc8aeMq9j+I/Jl79mem92wjn7NwrwmYfAziF6IaKZpDaIph64DdrfoesosCAwEAAQ==
spring.datasource.accessudp.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${spring.datasource.accessudp.publicKey}
spring.datasource.accessudp.initialSize=5
spring.datasource.accessudp.minIdle=5
spring.datasource.accessudp.maxActive=20
spring.datasource.accessudp.maxWait=60000
spring.datasource.accessudp.timeBetweenEvictionRunsMillis=60000
spring.datasource.accessudp.minEvictableIdleTimeMillis=300000
spring.datasource.accessudp.validationQuery=SELECT 1 FROM DUAL
spring.datasource.accessudp.testWhileIdle=true
spring.datasource.accessudp.testOnBorrow=false
spring.datasource.accessudp.testOnReturn=false
spring.datasource.accessudp.filters=config,wall,log4j,stat
spring.datasource.accessudp.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.accessudp.useGlobalDataSourceStat=true