package com.yjh.platform.common.tradio;

import com.sun.jna.*;
import com.sun.jna.ptr.LongByReference;

import java.nio.ByteBuffer;
import java.nio.LongBuffer;

/**
 * JNA Wrapper for library <b>Tradio</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface TradioLibrary extends Library {
    public static final String JNA_LIBRARY_NAME = "/usr/lib64/libtradio.so";
//    public static final String JNA_LIBRARY_NAME = "D:\\work\\iom\\IotCenter\\iot-center-platform\\src\\main\\resources\\lib\\TradioCp.dll";
//    public static final String JNA_LIBRARY_NAME = "F:\\IotCenter\\iot-center-platform\\src\\main\\resources\\lib\\TradioCp.dll";
//    public static final String JNA_LIBRARY_NAME = "E:\\project\\IotCenter\\IotCenter\\iot-center-platform\\src\\main\\resources\\lib\\TradioCp.dll";
//    public static final String JNA_LIBRARY_NAME = "D:\\code\\zhihui\\IotCenter\\iot-center-platform\\src\\main\\resources\\lib\\TradioCp.dll";
//    public static final String JNA_LIBRARY_NAME = "D:\\IOT\\IotCenter\\iot-center-platform\\src\\main\\resources\\lib\\TradioCp.dll";
//    public static final String JNA_LIBRARY_NAME = "D:\\MyDocuments\\workspace_idea\\IotCenterDev\\IotCenter\\iot-center-platform\\src\\main\\resources\\lib\\TradioCp.dll";
    public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(TradioLibrary.JNA_LIBRARY_NAME);
    public static final TradioLibrary INSTANCE = (TradioLibrary)Native.loadLibrary(TradioLibrary.JNA_LIBRARY_NAME, TradioLibrary.class);
    /**
     * NET_TRADIO_SetChannelOption opt define<br>
     * <i>native declaration : Tradio.h:71</i><br>
     * enum values
     */
    public static interface OptionType {
        /** <i>native declaration : Tradio.h:71</i> */
        public static final int TRADIO_CHANNEL_OPT_ELIMINATE_TVVOICE = 0x0001;
    };
    /** <i>native declaration : Tradio.h</i> */
    public interface PRtpCallback extends Callback {
        void apply(Pointer data, int size, int channel, int db, int sample_rate, long cookie);
    };
    /**
     * Original signature : <code>int NET_TRADIO_Init()</code><br>
     * <i>native declaration : Tradio.h:79</i>
     */
    int NET_TRADIO_Init();
    /**
     * Original signature : <code>int NET_TRADIO_DeviceReboot(const char*, int)</code><br>
     * <i>native declaration : Tradio.h:80</i><br>
     * @deprecated use the safer methods {@link #NET_TRADIO_DeviceReboot(String, int)} and {@link #NET_TRADIO_DeviceReboot(com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int NET_TRADIO_DeviceReboot(Pointer ip, int port);
    /**
     * Original signature : <code>int NET_TRADIO_DeviceReboot(const char*, int)</code><br>
     * <i>native declaration : Tradio.h:80</i>
     */
    int NET_TRADIO_DeviceReboot(String ip, int port);
    /**
     * Original signature : <code>int NET_TRADIO_TestDevice(const char*, int, int, NET_TRADIO_DEVICEINFO*)</code><br>
     * <i>native declaration : Tradio.h:81</i><br>
     * @deprecated use the safer methods {@link #NET_TRADIO_TestDevice(String, int, int, tradio.NET_TRADIO_DEVICEINFO)} and {@link #NET_TRADIO_TestDevice(com.sun.jna.Pointer, int, int, tradio.NET_TRADIO_DEVICEINFO)} instead
     */
    @Deprecated
    int NET_TRADIO_TestDevice(Pointer ip, int port, int timeout, NET_TRADIO_DEVICEINFO info);
    /**
     * Original signature : <code>int NET_TRADIO_TestDevice(const char*, int, int, NET_TRADIO_DEVICEINFO*)</code><br>
     * <i>native declaration : Tradio.h:81</i>
     */
    int NET_TRADIO_TestDevice(String ip, int port, int timeout, NET_TRADIO_DEVICEINFO info);
    /**
     * Original signature : <code>int NET_TRADIO_CreateDevice(unsigned long long*)</code><br>
     * <i>native declaration : Tradio.h:82</i><br>
     * @deprecated use the safer methods {@link #NET_TRADIO_CreateDevice(LongBuffer)} and {@link #NET_TRADIO_CreateDevice(com.sun.jna.ptr.LongByReference)} instead
     */
    @Deprecated
    int NET_TRADIO_CreateDevice(LongByReference hd);
    /**
     * Original signature : <code>int NET_TRADIO_CreateDevice(unsigned long long*)</code><br>
     * <i>native declaration : Tradio.h:82</i>
     */
    int NET_TRADIO_CreateDevice(LongBuffer hd);
    /**
     * Original signature : <code>int NET_TRADIO_SetRtpCallback(unsigned long long, PRtpCallback, long long)</code><br>
     * <i>native declaration : Tradio.h:83</i>
     */
    int NET_TRADIO_SetRtpCallback(long hd, PRtpCallback cb, long cookie);
    /**
     * Original signature : <code>int NET_TRADIO_Login(unsigned long long, const char*, int, const char*, const char*, NET_TRADIO_DEVICEINFO*)</code><br>
     * <i>native declaration : Tradio.h:84</i><br>
     * @deprecated use the safer methods {@link #NET_TRADIO_Login(long, String, int, String, String, tradio.NET_TRADIO_DEVICEINFO)} and {@link #NET_TRADIO_Login(long, com.sun.jna.Pointer, int, com.sun.jna.Pointer, com.sun.jna.Pointer, tradio.NET_TRADIO_DEVICEINFO)} instead
     */
    @Deprecated
    int NET_TRADIO_Login(long hd, Pointer ip, int port, Pointer usr, Pointer pwd, NET_TRADIO_DEVICEINFO info);
    /**
     * Original signature : <code>int NET_TRADIO_Login(unsigned long long, const char*, int, const char*, const char*, NET_TRADIO_DEVICEINFO*)</code><br>
     * <i>native declaration : Tradio.h:84</i>
     */
    int NET_TRADIO_Login(long hd, String ip, int port, String usr, String pwd, NET_TRADIO_DEVICEINFO info);
    /**
     * Original signature : <code>int NET_TRADIO_SetDeviceTime(unsigned long long, long)</code><br>
     * <i>native declaration : Tradio.h:85</i>
     */
    int NET_TRADIO_SetDeviceTime(long hd, NativeLong now_time);
    /**
     * Original signature : <code>int NET_TRADIO_SetAdVolume(unsigned long long, int)</code><br>
     * <i>native declaration : Tradio.h:86</i>
     */
    int NET_TRADIO_SetAdVolume(long hd, int volume);
    /**
     * Original signature : <code>int NET_TRADIO_SetChannelOption(unsigned long long, int, int, int)</code><br>
     * <i>native declaration : Tradio.h:87</i>
     */
    int NET_TRADIO_SetChannelOption(long hd, int channelNo, int opt, int val);
    /**
     * Original signature : <code>int NET_TRADIO_StartRemoteRecordFile(unsigned long long, int, const char*)</code><br>
     * <i>native declaration : Tradio.h:88</i><br>
     * @deprecated use the safer methods {@link #NET_TRADIO_StartRemoteRecordFile(long, int, String)} and {@link #NET_TRADIO_StartRemoteRecordFile(long, int, com.sun.jna.Pointer)} instead
     */
    @Deprecated
    int NET_TRADIO_StartRemoteRecordFile(long hd, int channelNo, Pointer filename);
    /**
     * Original signature : <code>int NET_TRADIO_StartRemoteRecordFile(unsigned long long, int, const char*)</code><br>
     * <i>native declaration : Tradio.h:88</i>
     */
    int NET_TRADIO_StartRemoteRecordFile(long hd, int channelNo, String filename);
    /**
     * Original signature : <code>int NET_TRADIO_StopRemoteRecordFile(unsigned long long, int, char*, int)</code><br>
     * <i>native declaration : Tradio.h:89</i><br>
     * @deprecated use the safer methods {@link #NET_TRADIO_StopRemoteRecordFile(long, int, ByteBuffer, int)} and {@link #NET_TRADIO_StopRemoteRecordFile(long, int, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int NET_TRADIO_StopRemoteRecordFile(long hd, int channelNo, Pointer filename, int size);
    /**
     * Original signature : <code>int NET_TRADIO_StopRemoteRecordFile(unsigned long long, int, char*, int)</code><br>
     * <i>native declaration : Tradio.h:89</i>
     */
    int NET_TRADIO_StopRemoteRecordFile(long hd, int channelNo, ByteBuffer filename, int size);
    /**
     * Original signature : <code>int NET_TRADIO_RemoteRecordFileName(unsigned long long, int, char*, int)</code><br>
     * <i>native declaration : Tradio.h:90</i><br>
     * @deprecated use the safer methods {@link #NET_TRADIO_RemoteRecordFileName(long, int, ByteBuffer, int)} and {@link #NET_TRADIO_RemoteRecordFileName(long, int, com.sun.jna.Pointer, int)} instead
     */
    @Deprecated
    int NET_TRADIO_RemoteRecordFileName(long hd, int channelNo, Pointer filename, int size);
    /**
     * Original signature : <code>int NET_TRADIO_RemoteRecordFileName(unsigned long long, int, char*, int)</code><br>
     * <i>native declaration : Tradio.h:90</i>
     */
    int NET_TRADIO_RemoteRecordFileName(long hd, int channelNo, ByteBuffer filename, int size);
    /**
     * Original signature : <code>int NET_TRADIO_Logout(unsigned long long)</code><br>
     * <i>native declaration : Tradio.h:91</i>
     */
    int NET_TRADIO_Logout(long hd);
    /**
     * Original signature : <code>int NET_TRADIO_ReleaseDevice(unsigned long long)</code><br>
     * <i>native declaration : Tradio.h:92</i>
     */
    int NET_TRADIO_ReleaseDevice(long hd);
    /**
     * Original signature : <code>int NET_TRADIO_Clear()</code><br>
     * <i>native declaration : Tradio.h:93</i>
     */
    int NET_TRADIO_Clear();
}
