logging:
  level:
    ROOT: info
    com.yjh: info
  file:
    name: ./logs/ainterface.log
  charset:
    console: utf-8
    file: utf-8

spring:
  application:
    name: demo
  profiles:
    active: prod
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /demo
  port: 18088

send:
  batch: false

task:
  thread:
    count: 10

default:
  params:
    robotCode: E100-0001
    droneCode: Drone-0001
    nestCode: Nest-0001