plugins {
    id 'org.springframework.boot' version '2.4.2'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = 'com.yjh'
version = '1.1'
sourceCompatibility = '1.8'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/public/' }
    maven { url 'https://maven.aliyun.com/repository/spring/' }
    mavenCentral()
    maven {
        allowInsecureProtocol = true
        url "http://192.168.9.53:8081/repository/maven-snapshots/"
    }
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.zalando:problem-spring-web-starter:0.26.2'

    implementation 'com.github.xiaoymin:knife4j-spring-boot-starter:2.0.3'
    implementation 'org.freemarker:freemarker:2.3.28'

    compileOnly 'org.projectlombok:lombok:1.18.22'

    annotationProcessor 'org.projectlombok:lombok:1.18.22'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    implementation 'com.yjh:protocol-a-core:0.2-SNAPSHOT'

    implementation 'commons-net:commons-net:3.6'

    implementation 'com.alibaba:fastjson:1.2.49'

}

test {
    useJUnitPlatform()
}
