#IP 配置
#本机ip
host.ip=172.24.39.9
#算法主机ip
algorithm.ip=172.24.39.9
#支持那种协议 http https
protocol=https
#tomcat config
spring.application.name=iot-center-platform
server.port=18711
server.session-timeout=1800
server.tomcat.uri-encoding=utf-8
server.tomcat.max-threads=500
server.servlet.context-path=
server.servlet.path=/
server.tomcat.access-log-pattern=%t [%a] [%I] [%H-%m] %U %s %T
server.tomcat.access-log-enabled=true
#server.tomcat.basedir=/webapp/temp
#注册中心
#Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
eureka.instance.lease-renewal-interval-in-seconds=5
#Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
eureka.instance.lease-expiration-duration-in-seconds=15
#缓存清单更新时间默认值30秒 #拉取服务列表的时间间隔，每隔5秒去注册中心拉取服务列表
eureka.client.registry-fetch-interval-seconds=5
eureka.client.serviceUrl.defaultZone=http://${host.ip}:18710/eureka/
eureka.instance.prefer-ip-address=true
#actuator监控
management.endpoints.web.exposure.include=metrics
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
#mybatis 下划线自动转驼峰
mybatis.configuration.mapUnderscoreToCamelCase=true
#mybatis plus 下划线自动转驼峰
mybatis-plus.configuration.mapUnderscoreToCamelCase=true
mybatis-plus.mapperLocations=classpath:/mybatis/mapper/*.xml
#DB mysql configuration:
spring.datasource.platform.driverClassName=com.mysql.jdbc.Driver
spring.datasource.platform.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.platform.url=jdbc:mysql://${host.ip}:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
spring.datasource.platform.username=root
#spring.datasource.platform.password=yjh@123!
spring.datasource.platform.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.datasource.platform.publicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL19LiGbPzoLBZJvUqZoxeEeknRpuGc8aeMq9j+I/Jl79mem92wjn7NwrwmYfAziF6IaKZpDaIph64DdrfoesosCAwEAAQ==
spring.datasource.platform.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${spring.datasource.platform.publicKey}
# 下面为连接池的补充设置，应用到上面所有数据源中
spring.datasource.platform.initialSize=5
spring.datasource.platform.minIdle=5
spring.datasource.platform.maxActive=20
# 配置获取连接等待超时的时间
spring.datasource.platform.maxWait=30000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource.platform.timeBetweenEvictionRunsMillis=60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource.platform.minEvictableIdleTimeMillis=300000
spring.datasource.platform.validationQuery=SELECT 1 FROM DUAL
spring.datasource.platform.testWhileIdle=true
spring.datasource.platform.testOnBorrow=false
spring.datasource.platform.testOnReturn=false
# druid数据源监控web
spring.datasource.platform.filters=config,wall,log4j,stat
spring.datasource.platform.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.platform.useGlobalDataSourceStat=true 
#spring.redis.host=localhost
#spring.redis.port=6379
spring.servlet.multipart.max-file-size=1000Mb
spring.servlet.multipart.max-request-size=1000Mb
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

# Redis数据库索引（默认为0）
spring.redis.database=0
# Redis服务器地址
spring.redis.host=${host.ip}
# Redis服务器连接端口
spring.redis.port=6379
# Redis服务器连接密码（默认为空）
spring.redis.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-idle=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1
# 连接池中的最大空闲连接
spring.redis.jedis.pool.max-active=8
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=0
# 连接超时时间（毫秒）
spring.redis.timeout=0
#用户重置密码的初始密码
user.password=123456

#quartz配置
spring.quartz.auto-startup=true
spring.quartz.job-store-type=jdbc
spring.quartz.schedulerName=PlatformScheduler
spring.quartz.properties.org.quartz.scheduler.instanceName=PlatformSchedulerInstance
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=true
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval=5000
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=60000
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount=25
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
spring.quartz.properties.org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true
spring.servlet.multipart.location=/home/yjh_iot_center/iot-files/temporaryFiles
server.compression.enabled=true
server.compression.mime-types=application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain


# 秒级静默监视任务cron表达式
seconds.silent.task.cron=0 */2 * * * ?
#设备可靠性上报时间
spring.device.time=0 0 10 * * ?

#27大类数据配置文件
spring.inspection.conf=inspectionConf.json
#顺控是否自定义结果 0-否 1-是
spring.sequential.result.flag=0

# 是否拦截参数篡改
sys.param.secure.isDecode=true
# 是否开启加解密
sys.param.secure.isEncryption=true
# 是否开启Ukey
sys.param.secure.isUkey=false
# 是否开启ip篡改验证
sys.param.secure.isIp=false
# 是否开启用户登录ip验证
sys.param.secure.isIpLogin=true
# 后端统一非法字符校验
sys.param.secure.paramsValidate=true
# 是否用户唯一，删除后也不可创建同名用户
sys.param.secure.uniqueUser=true


#报表绝对路径
nginx.report.reflect=/home/yjh_iot_center/iot-files/reportFiles
#临时文件路径
nginx.temporary.reflect=/home/yjh_iot_center/iot-files/temporaryFiles
#报表相对路径
nginx.reportRelative.reflect=http://${host.ip}:10086/files/reportFiles
video.videoUrl.path=http://${host.ip}:18715/camera/v1/getVidemoIntercomStatus
#jobName
spring.QingHua.jobName=qhTest
#获取关键服务的接口url
spring.Key.Services.path=http://${host.ip}:18710/managerService/v1/select

#websocket服务url
spring.websocket.send.url=http://${host.ip}:18701/route/syncWebsocket
#相机抓图
sequential.cameraCapture=http://${host.ip}:18715/camera/v1/capturePicture
#相机开始录制视频
sequential.startRecordVideo=http://${host.ip}:18715/camera/v1/startRecordVideo
#相机结束录制视频
sequential.endRecordVideo=http://${host.ip}:18715/camera/v1/endRecordVideo
#算法图片识别
sequential.picRec=http://iot-center-accessvideo/analysis/v1/algorithm

# 智能分析主机相关配置
# 请求图像分析接口
intelligent.algorithm.analysis-url=http://${algorithm.ip}:20011/picAnalyse
# 请求算法更新接口
intelligent.algorithm.update-url=http://${algorithm.ip}:20013/algorithmUpdate
# 分析结果反馈ip地址
intelligent.algorithm.result-ip=${host.ip}
# 分析结果返回端口
intelligent.algorithm.result-port=18715
# 静默监视告警类型识别
intelligent.algorithm.silent-monitor-type=sly_bjbmyw,sly_dmyw,pzqcd,drqgd,yxdghsg,dxdg,hzyw,yw_gkxfw,xdwcr,wcaqm,wcgz,ryjjph
# 18类缺陷类型
intelligent.algorithm.defect-type=bj_bpmh,bj_bpps,bj_wkps,jyz_pl,sly_bjbmyw,sly_dmyw,hxq_gjtps,xmbhyc,yw_gkxfw,yw_nc,gbps,wcaqm,wcgz,xy,bjdsyc,ywzt_yfyc,hxq_gjbs,kgg_ybh
# 判别类型
intelligent.algorithm.distinguish-type=tx_pb
# 静默监视类型 key:value   静默监视文字告警类型:数字
# 安全帽:1,工作服:3,人员:4,场地烟火:101,小动物:103,设备烟火:201,渗漏油:202,悬浮物:204,设备变形:205,设备断裂:206,设备倾斜:207
intelligent.algorithm.silent-monitor-name-and-type=安全帽:1,工作服:3,人员:4,场地烟火:101,小动物:103,设备烟火:201,渗漏油:202,悬浮物:204,设备变形:205,设备断裂:206,设备倾斜:207,异物:204,膨胀器冲顶:205,电容器鼓肚:206,引线断股或松股:206,导线断股:206,火灾烟雾:101
>>>>>>> dev-feature-0630

#节点级别  1:边缘节点;2:巡视主机;3:上级系统
sys.param.edge.level=2
#节点分配  边缘节点(1~1999) 巡视主机(2000~2999) 上级系统(3000~3999)
sys.param.edge.code=Region01
sys.param.edge.id=1
# 变电站2000
sys.param.edge.name=巡视主机1
#文件路径配置
#机器人巡检结果图片绝对路径
sys.param.secure.ftpImageAbsolute=/home/yjh_iot_center/iot-picture/ftpImg
#机器人巡检结果图片相对路径
sys.param.secure.ftpImageRelative=${protocol}://${host.ip}/imgs/ftpImg
#压缩包绝对路径
sys.param.secure.zipPath=/home/yjh_iot_center/iot-picture/zip
#压缩包相对路径
sys.param.secure.zipRealPath=${protocol}://${host.ip}/imgs/zip
#模型文件绝对路径
sys.param.secure.modelAbsolutePath=/home/yjh_iot_center/iot-files/tcpFiles
#模型文件的相对路径
sys.param.secure.modelRelativePath=${protocol}://${host.ip}/files/tcpFiles
#音频文件相对路径
sys.param.secure.absVoicePath=/home/yjh_iot_center/iot-files/voiceFile
#音频文件绝对路径
sys.param.secure.relativeVoicePath=${protocol}://${host.ip}/files/voiceFile
#缺陷识别算法图片绝对路径
sys.param.secure.defectResultImg=/home/yjh_iot_center/iot-picture/analyseResultImg/defect
#缺陷算法图片存储相对路径
sys.param.secure.defectResultRealImg=${protocol}://${host.ip}/imgs/analyseResultImg/defect
#表计识别算法结果图片存储绝对路径
sys.param.secure.meterResultImg=/home/yjh_iot_center/iot-picture/analyseResultImg/meter
#表计识别算法结果图片存储相对路径
sys.param.secure.meterResultRealImg=${protocol}://${host.ip}/imgs/analyseResultImg/meter
#设备类型图片存储绝对路径
sys.param.secure.deviceTypeImgAbsPath=/home/yjh_iot_center/iot-files/deviceTypeImage
#设备类型图片存储相对路径
sys.param.secure.deviceTypeImgReaPath=${protocol}://${host.ip}/files/deviceTypeImage
#判别算法图片存储绝对路径
sys.param.secure.judgeResultImg=/home/yjh_iot_center/iot-picture/analyseResultImg/panbie/
#判别算法图片存储相对路径
sys.param.secure.judgeResultRealImg=${protocol}://${host.ip}/imgs/analyseResultImg/panbie
#红外文件存储绝对路径
sys.param.secure.infraredStorePath=/home/yjh_iot_center/iot-picture/infrared/
#红外文件存储相对路径
sys.param.secure.infraredRealPath=${protocol}://${host.ip}/imgs/infrared/
#相机抓图存储相对路径
sys.param.secure.resultImgPath=/home/yjh_iot_center/iot-picture/resultImg/
#模板图片路径
sys.param.secure.resultImgRealPath=${protocol}://${host.ip}/imgs/resultImg/
#预置位图片存储相对路径
sys.param.secure.presetImgPath=/home/yjh_iot_center/iot-picture/specimens
#预置位图片存储绝对路径
sys.param.secure.presetRealImgPath=${protocol}://${host.ip}/imgs/specimens
#存储绝对路径前缀
sys.param.secure.prefixAbsolutePath=/home/yjh_iot_center/iot-picture/
#存储相对路径前缀
sys.param.secure.prefixRelativePath=${protocol}://${host.ip}/imgs/
#文件映射相对路径
sys.param.secure.fileAbsPath=/home/yjh_iot_center/iot-files/
#文件映射绝对路径
sys.param.secure.fileRealPath=${protocol}://${host.ip}/files/
#视频录制绝对路径
sys.param.secure.videoPath=/home/yjh_iot_center/iot-picture/video/
#视频录制相对路径
sys.param.secure.videoRealPath=${protocol}://${host.ip}/imgs/video/
#sdk lib包位置
sys.param.secure.sdkPath=/config/lib_arm64
#1普通抓图 2 dlt664抓图
sys.param.secure.givePic=2
