#tomcat config
spring.application.name=iot-center-platform
server.port=18711
server.session-timeout=1800
server.tomcat.uri-encoding=utf-8
server.tomcat.max-threads=500
server.servlet.context-path=
server.servlet.path=/
server.tomcat.access-log-pattern=%t [%a] [%I] [%H-%m] %U %s %T
server.tomcat.access-log-enabled=true
#server.tomcat.basedir=../tomcat
#注册中心
#Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
eureka.instance.lease-renewal-interval-in-seconds=5
#Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
eureka.instance.lease-expiration-duration-in-seconds=15
#缓存清单更新时间默认值30秒 #拉取服务列表的时间间隔，每隔5秒去注册中心拉取服务列表
eureka.client.registry-fetch-interval-seconds=5
eureka.client.serviceUrl.defaultZone=http://127.0.0.1:8081/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
#mybatis 下划线自动转驼峰
mybatis.configuration.mapUnderscoreToCamelCase=true
#mybatis.configuration.map-underscore-to-camel-case=true
#DB mysql configuration:
spring.datasource.platform.driverClassName=com.mysql.jdbc.Driver
spring.datasource.platform.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.platform.url=jdbc:mysql://127.0.0.1:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
spring.datasource.platform.username=root
#spring.datasource.platform.password=yjh@123!
spring.datasource.platform.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.datasource.platform.publicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL19LiGbPzoLBZJvUqZoxeEeknRpuGc8aeMq9j+I/Jl79mem92wjn7NwrwmYfAziF6IaKZpDaIph64DdrfoesosCAwEAAQ==
spring.datasource.platform.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${spring.datasource.platform.publicKey}
# 下面为连接池的补充设置，应用到上面所有数据源中
spring.datasource.platform.initialSize=5
spring.datasource.platform.minIdle=5
spring.datasource.platform.maxActive=20
# 配置获取连接等待超时的时间
spring.datasource.platform.maxWait=60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource.platform.timeBetweenEvictionRunsMillis=60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource.platform.minEvictableIdleTimeMillis=300000
spring.datasource.platform.validationQuery=SELECT 1 FROM DUAL
spring.datasource.platform.testWhileIdle=true
spring.datasource.platform.testOnBorrow=false
spring.datasource.platform.testOnReturn=false
# druid数据源监控web
spring.datasource.platform.filters=config,wall,log4j,stat
spring.datasource.platform.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.platform.useGlobalDataSourceStat=true
#spring.redis.host=localhost
#spring.redis.port=6379
spring.servlet.multipart.max-file-size=1000Mb
spring.servlet.multipart.max-request-size=1000Mb
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
#common config
#服务所在根路径
service.common.serverPath=/opt/app/1
#
##kafka 配置
#spring.kafka.bootstrap-servers=s-appserver-168:9092
#spring.kafka.consumer.auto-offset-reset=latest
#spring.kafka.consumer.group-id=znv-manager
# Redis数据库索引（默认为0）
spring.redis.database=0
# Redis服务器地址
#spring.redis.host=122.112.250.192
spring.redis.host=127.0.0.1
#spring.redis.host=192.168.30.248
# Redis服务器连接端口
spring.redis.port=6379
# Redis服务器连接密码（默认为空）
spring.redis.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
#spring.redis.password=XXTVywwUME6KRwHRh0oNHQ==
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-idle=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1
# 连接池中的最大空闲连接
spring.redis.jedis.pool.max-active=8
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=0
# 连接超时时间（毫秒）
spring.redis.timeout=0
#用户重置密码的初始密码
user.password=123456
#zipkin 使用
#spring.zipkin.rabbitmq.queue=zipkin
#spring.zipkin.sender.type=rabbit
#spring.zipkin.locator.discovery.enabled=true
#spring.sleuth.sampler.probability=1.0
#spring.rabbitmq.host=10.45.156.238
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=admin
#spring.rabbitmq.password=admin
#spring.zipkin.base-url=http://10.45.156.192:9411
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=ALWAYS
#默认feign的hystrix为关闭状态
feign.hystrix.enabled=true
hystrix.command.default.execution.isolation.strategy=SEMAPHORE
#fegin调用
#请求处理的超时时间
ribbon.ReadTimeout=60000
#请求连接的超时时间
ribbon.ConnectTimeout=60000

user.dir=F:\workspace\jiejuefangan\IotCenter\iot-center-platform

#quartz配置
spring.quartz.auto-startup=true
spring.quartz.job-store-type=jdbc
spring.quartz.schedulerName=PlatformScheduler
spring.quartz.properties.org.quartz.scheduler.instanceName=PlatformSchedulerInstance
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.properties.org.quartz.jobStore.useProperties=true
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval=5000
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=60000
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount=25
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
spring.quartz.properties.org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true

#周期上报时间 单位秒
data.period.upload.interval=5

# ??TCP????
audio.tcp.server.port=10021

#是否调用调用算法组相机偏移校验功能
camera.preset.second.check=false