#tomcat config
spring.application.name=iot-center-accessvideo
server.port=18715
server.session-timeout=1800
server.tomcat.uri-encoding=utf-8
server.tomcat.max-threads=500
server.servlet.context-path=
server.servlet.path=/
server.tomcat.accessVideo-log-pattern=%t [%a] [%I] [%H-%m] %U %s %T
server.tomcat.accessVideo-log-enabled=true
#server.tomcat.basedir=../tomcat
#\u6CE8\u518C\u4E2D\u5FC3
#Eureka\u5BA2\u6237\u7AEF\u5411\u670D\u52A1\u7AEF\u53D1\u9001\u5FC3\u8DF3\u7684\u65F6\u95F4\u95F4\u9694\uFF0C\u5355\u4F4D\u4E3A\u79D2\uFF08\u5BA2\u6237\u7AEF\u544A\u8BC9\u670D\u52A1\u7AEF\u81EA\u5DF1\u4F1A\u6309\u7167\u8BE5\u89C4\u5219\uFF09
eureka.instance.lease-renewal-intervalw-in-seconds=5
#Eureka\u670D\u52A1\u7AEF\u5728\u6536\u5230\u6700\u540E\u4E00\u6B21\u5FC3\u8DF3\u4E4B\u540E\u7B49\u5F85\u7684\u65F6\u95F4\u4E0A\u9650\uFF0C\u5355\u4F4D\u4E3A\u79D2\uFF0C\u8D85\u8FC7\u5219\u5254\u9664\uFF08\u5BA2\u6237\u7AEF\u544A\u8BC9\u670D\u52A1\u7AEF\u6309\u7167\u6B64\u89C4\u5219\u7B49\u5F85\u81EA\u5DF1\uFF09
eureka.instance.lease-expiration-duration-in-seconds=15
#\u7F13\u5B58\u6E05\u5355\u66F4\u65B0\u65F6\u95F4\u9ED8\u8BA4\u503C30\u79D2 #\u62C9\u53D6\u670D\u52A1\u5217\u8868\u7684\u65F6\u95F4\u95F4\u9694\uFF0C\u6BCF\u96945\u79D2\u53BB\u6CE8\u518C\u4E2D\u5FC3\u62C9\u53D6\u670D\u52A1\u5217\u8868
eureka.client.registry-fetch-interval-seconds=5
eureka.client.serviceUrl.defaultZone=http://192.168.9.40:18710/eureka/
eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
#mybatis \u4E0B\u5212\u7EBF\u81EA\u52A8\u8F6C\u9A7C\u5CF0
mybatis.configuration.mapUnderscoreToCamelCase=true
#mybatis.configuration.map-underscore-to-camel-case=true
#DB mysql configuration:
spring.datasource.accessvideo.driverClassName=com.mysql.jdbc.Driver
spring.datasource.accessvideo.type=com.alibaba.druid.pool.DruidDataSource

#spring.datasource.accessvideo.url=jdbc:mysql://127.0.0.1:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
spring.datasource.accessvideo.url=jdbc:mysql://192.168.9.40:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
#spring.datasource.accessvideo.url=jdbc:mysql://192.168.30.248:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true


spring.datasource.accessvideo.username=root
#spring.datasource.accessvideo.password=yjh@123!
spring.datasource.accessvideo.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.datasource.accessvideo.publicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL19LiGbPzoLBZJvUqZoxeEeknRpuGc8aeMq9j+I/Jl79mem92wjn7NwrwmYfAziF6IaKZpDaIph64DdrfoesosCAwEAAQ==
spring.datasource.accessvideo.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${spring.datasource.accessvideo.publicKey}
# \u4E0B\u9762\u4E3A\u8FDE\u63A5\u6C60\u7684\u8865\u5145\u8BBE\u7F6E\uFF0C\u5E94\u7528\u5230\u4E0A\u9762\u6240\u6709\u6570\u636E\u6E90\u4E2D
spring.datasource.accessvideo.initialSize=5
spring.datasource.accessvideo.minIdle=5
spring.datasource.accessvideo.maxActive=20
# \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
spring.datasource.accessvideo.maxWait=60000
# \u914D\u7F6E\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
spring.datasource.accessvideo.timeBetweenEvictionRunsMillis=60000
# \u914D\u7F6E\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
spring.datasource.accessvideo.minEvictableIdleTimeMillis=300000
spring.datasource.accessvideo.validationQuery=SELECT 1 FROM DUAL
spring.datasource.accessvideo.testWhileIdle=true
spring.datasource.accessvideo.testOnBorrow=false
spring.datasource.accessvideo.testOnReturn=false
# druid\u6570\u636E\u6E90\u76D1\u63A7web
spring.datasource.accessvideo.filters=config,wall,log4j,stat
spring.datasource.accessvideo.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.accessvideo.useGlobalDataSourceStat=true
#spring.redis.host=localhost
#spring.redis.port=6379
spring.servlet.multipart.max-file-size=1000Mb
spring.servlet.multipart.max-request-size=1000Mb
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
#common config
#\u670D\u52A1\u6240\u5728\u6839\u8DEF\u5F84
service.common.serverPath=/opt/app/1
#
##kafka \u914D\u7F6E
#spring.kafka.bootstrap-servers=s-appserver-168:9092
#spring.kafka.consumer.auto-offset-reset=latest
#spring.kafka.consumer.group-id=znv-manager
# Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
spring.redis.database=0
# Redis\u670D\u52A1\u5668\u5730\u5740
#spring.redis.host=122.112.250.192
spring.redis.host=192.168.9.40
#spring.redis.host=192.168.30.248
# Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
spring.redis.port=6379
# Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
#spring.redis.password=RXzOTarkaH1+1rwn4T6fvWK05FDshW+8RTquOYDxIvOcmueP+hWDnJtlZI7fRQwyjn+GTdIVlWmnzc+VrR5DhA==
spring.redis.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
# \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
spring.redis.jedis.pool.max-idle=8
# \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
spring.redis.jedis.pool.max-wait=-1
# \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
spring.redis.jedis.pool.max-active=8
# \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
spring.redis.jedis.pool.min-idle=0
# \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
spring.redis.timeout=0
#\u7528\u6237\u91CD\u7F6E\u5BC6\u7801\u7684\u521D\u59CB\u5BC6\u7801
user.password=123456
#zipkin \u4F7F\u7528
#spring.zipkin.rabbitmq.queue=zipkin
#spring.zipkin.sender.type=rabbit
#spring.zipkin.locator.discovery.enabled=true
#spring.sleuth.sampler.probability=1.0
#spring.rabbitmq.host=10.45.156.238
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=admin
#spring.rabbitmq.password=admin
#spring.zipkin.base-url=http://10.45.156.192:9411
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=ALWAYS
#\u9ED8\u8BA4feign\u7684hystrix\u4E3A\u5173\u95ED\u72B6\u6001
feign.hystrix.enabled=true
hystrix.command.default.execution.isolation.strategy=SEMAPHORE
#fegin\u8C03\u7528
#\u8BF7\u6C42\u5904\u7406\u7684\u8D85\u65F6\u65F6\u95F4
ribbon.ReadTimeout=60000
#\u8BF7\u6C42\u8FDE\u63A5\u7684\u8D85\u65F6\u65F6\u95F4
ribbon.ConnectTimeout=60000

user.dir=F:/IotCenter/iot-center-accessvideo

#TC MQ
rmq.host=220.248.75.10
rmq.port=5672
rmq.name=tiecheng
rmq.password=tiecheng
rmq.vhost=/algorithm
rmq.route=iot_exc
rmq.taskquename.robotInfo=robotinfo
rmq.taskquename.robotState=robotstate
rmq.taskquename.taskData=taskdata
rmq.taskquename.taskResult=taskresult
rmq.type1=direct
rmq.type2=fanout
rmq.type3=topic
rmq.type4=headers

nvr.sdk.path=/home/yjh_iot_center/iot-center-accessvideo-1.0.0/config/lib
nvr.log.path=/home/yjh_iot_center/iot-center-accessvideo-1.0.0/sdk_log/
nvr.log.level=3
nvr.capture.result=/home/yjh_iot_center/iot-picture/resultImg
nvr.capture.Preset=/home/yjh_iot_center/iot-picture/presets
#                /usr/bin/ffmpeg -rtsp_transport tcp -i rtsp://admin:Yijiahe123@192.168.33.2:557/Streaming/Channels/101?transportmode=unicast -vcodec copy -fflags nobuffer -analyzeduration 0 -f flv -an rtmp://172.24.39.108:11935/live/123
nvr.rtmp.video=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s@%s:%s/Streaming/Channels/%s0%s?transportmode=unicast -vcodec copy -acodec copy -fflags nobuffer -analyzeduration 0 -f flv rtmp://172.24.39.108/live/%s
nvr.rtmp.back=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s@%s:%s/Streaming/tracks/%s0%s?starttime=%s\&endtime=%s -vcodec copy -acodec copy -f flv -r 15 -y rtmp://172.24.39.108/history/%s
nvr.download.trans=/usr/local/bin/ffmpeg -i %s -c copy -an %s
robot.light.video=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s@%s:%s/Streaming/Channels/10%s?transportmode=unicast -vcodec copy -fflags nobuffer -an -f flv rtmp://172.24.39.108/live/%s
robot.inferad.video=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s/camera0 -vcodec copy -fflags nobuffer -an -f flv rtmp://172.24.39.108/live/%s
robot.A200.infrared.video=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s/video -vcodec copy -fflags nobuffer -an -f flv rtmp://172.24.39.108/live/%s
nginx.picture.preset=http://172.24.39.108:10086/imgs/presets

#1-\u9AD8\u6E05\u89C6\u9891\uFF0C2-\u666E\u901A\u89C6\u9891
realtime.video.definition=1
#1-https\uFF0C2-http
video.https.enable=1
#srsUrl
srs.stop.url=172.24.39.108

#\u63A5\u5165\u670D\u52A1\u5668\u7684IP\u548C\u7AEF\u53E3
netty.recognize.port=13668
netty.ai.port=13669
netty.server.url=192.168.9.37
nginx.picture.reflact=http://172.24.39.108:10086/imgs/resultImg
nvr.capture.video=/home/yjh_iot_center/iot-picture/video/
nvr.capture.savePath=http://172.24.39.108:10086/imgs/video/
nvr.capture.hotPic=/home/yjh_iot_center/iot-picture/resultImg/
nvr.capture.hotPicshow=http://172.24.39.108:10086/imgs/resultImg/
nvr.capture.hotFir=/home/yjh_iot_center/iot-picture/infrared/
nvr.capture.hotFirShow=http://172.24.39.108:10086/imgs/infrared/
service.video.Path=http://172.24.39.108:18711/videoIntercom/v1/selectByPrimaryId

#webSocket\u8DEF\u5F84\u914D\u7F6E
system.webSocket.url=http://172.24.39.108:18701/route/syncWebsocket

spring.interface.api=false

# \u667A\u80FD\u5206\u6790\u4E3B\u673A\u76F8\u5173\u914D\u7F6E
# \u8BF7\u6C42\u56FE\u50CF\u5206\u6790\u63A5\u53E3
intelligent.algorithm.analysis-url=http://127.0.0.1:18711/picAnalyse
# \u8BF7\u6C42\u7B97\u6CD5\u66F4\u65B0\u63A5\u53E3
intelligent.algorithm.update-url=http://172.24.39.108:20013/algorithmUpdate
# \u5206\u6790\u7ED3\u679C\u53CD\u9988ip\u5730\u5740
intelligent.algorithm.result-ip=172.24.39.108
# \u5206\u6790\u7ED3\u679C\u8FD4\u56DE\u7AEF\u53E3
intelligent.algorithm.result-port=18715
# \u9759\u9ED8\u76D1\u89C6\u544A\u8B66\u7C7B\u578B\u8BC6\u522B
intelligent.algorithm.silent-monitor-type=sly_dmyw,yw_gkxfw,yw_nc,gbps,xmbhyc,xmbhzc,kgg_ybh,kgg_ybf,wcaqm,wcgz,gzzc,xy,jyz_pl,byq_hxq,hxq_gjbs,hxq_gjzc,hxq_gjtps,ywzt_yfyc,bj_bpmh,bj_bpps,bj_wkps,bjdsyc,bjzc,bj_sxb,sxb_bjdsyc,sxb_bjdszc,bj
# 18\u7C7B\u7F3A\u9677\u7C7B\u578B
intelligent.algorithm.defect-type=sly_dmyw,yw_gkxfw,yw_nc,gbps,xmbhyc,kgg_ybh,kgg_ybf,wcaqm,wcgz,xy,jyz_pl,hxq_gjbs,hxq_gjtps,ywzt_yfyc,bj_bpmh,bj_bpps,bj_wkps,bjdsyc
# \u5224\u522B\u7C7B\u578B
intelligent.algorithm.distinguish-type=tx_pb
# 27\u5927\u7C7B\u4F5C\u5047\u6570\u636E\u8BFB\u53D6\u914D\u7F6E\u6587\u4EF6
conf.file.name=inspectionConf.json

# \u7B97\u6CD5\u7BA1\u7406\u5E73\u53F0ftps\u914D\u7F6E
manager.server.ftps.flag=1
manager.server.ftps.ip=172.24.39.108
manager.server.ftps.port=10012
manager.server.ftps.username=ftpuser
manager.server.ftps.password=ttasdqwe123
manager.server.ftps.keypw=1
manager.server.ftps.remote.path=\u5357\u4EAC/\u96E8\u82B1\u53F0\u533A\u57DF/500kV\u53D8\u7535\u7AD9

# \u5DE1\u89C6\u4E3B\u673Aftps\u914D\u7F6E
intelligent.server.ftps.flag=1
intelligent.server.ftps.ip=172.24.39.108
intelligent.server.ftps.port=10012
intelligent.server.ftps.username=ftpuser
intelligent.server.ftps.password=ttasdqwe123
intelligent.server.ftps.keypw=1
intelligent.server.ftps.remote.path=/home/yjh_iot_center/ftps

# \u4E0A\u7EA7\u7CFB\u7EDFftps\u914D\u7F6E
up.system.ftps.flag=1
up.system.ftps.ip=172.24.39.108
up.system.ftps.port=10012
up.system.ftps.username=ftpuser
up.system.ftps.password=ttasdqwe123
up.system.ftps.keypw=1
up.system.ftps.remote.path=/home/yjh_iot_center/ftps

#mqtt configinfo
mqtt.host=tcp://172.24.39.108:1883
mqtt.serverClientId=iot
mqtt.user=admin
mqtt.pwd=yjh@123!
mqtt.topic=nodes/java/user/alert/2
mqtt.province_name=\u6C5F\u82CF
mqtt.city_name=\u5357\u4EAC
mqtt.station_name=500kV\u6C5F\u82CF\u53D8\u7535\u7AD9
#\u672C\u673Aip
mqtt.section_ip=192.168.10.151
mqtt.node_id=1997030609
mqtt.volt_level=500

#\u7B97\u6CD5\u56FE\u7247\u8BC6\u522B\u8FD4\u56DE
sequential.picRecBack=http://172.24.39.108:18711/tSequentialConf/v1/sequentialRecBack

# \u53D8\u7535\u7AD9\u7F16\u7801
station.code=01
#1\u8C03\u7528\u539F\u6709\u63A5\u53E3 2\u8C03\u7528dlt\u6293\u56FE\u63A5\u53E3
give.pic=2

#\u5DE1\u89C6\u4E3B\u673A\u7684ftps\u914D\u7F6E
platform.system.ftps.flag=1
platform.system.ftps.ip=192.168.33.20
platform.system.ftps.port=10012
platform.system.ftps.username=ftpuser
platform.system.ftps.password=ttasdqwe123
platform.system.ftps.keypw=1
platform.system.ftps.remote.path=/home/yjh_iot_center/ftps

# \u662F\u5426\u5C06video\u670D\u52A1\u5355\u72EC\u90E8\u7F72
video.separate.deploy=false
