#tomcat config
spring.application.name=iot-center-accessvideo
server.port=18715
server.session-timeout=1800
server.tomcat.uri-encoding=utf-8
server.tomcat.max-threads=500
server.servlet.context-path=
server.servlet.path=/
server.tomcat.accessVideo-log-pattern=%t [%a] [%I] [%H-%m] %U %s %T
server.tomcat.accessVideo-log-enabled=true
#server.tomcat.basedir=../tomcat
#注册中心
#Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
eureka.instance.lease-renewal-intervalw-in-seconds=5
#Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
eureka.instance.lease-expiration-duration-in-seconds=15
#缓存清单更新时间默认值30秒 #拉取服务列表的时间间隔，每隔5秒去注册中心拉取服务列表
eureka.client.registry-fetch-interval-seconds=5
eureka.client.serviceUrl.defaultZone=http://192.168.9.40:18999/eureka/
eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.cloud.client.ip-address}:${server.port}
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
#mybatis 下划线自动转驼峰
mybatis.configuration.mapUnderscoreToCamelCase=true
#mybatis.configuration.map-underscore-to-camel-case=true
#DB mysql configuration:
spring.datasource.accessvideo.driverClassName=com.mysql.jdbc.Driver
spring.datasource.accessvideo.type=com.alibaba.druid.pool.DruidDataSource

#spring.datasource.accessvideo.url=jdbc:mysql://127.0.0.1:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
spring.datasource.accessvideo.url=jdbc:mysql://192.168.9.40:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
#spring.datasource.accessvideo.url=jdbc:mysql://192.168.30.248:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true


spring.datasource.accessvideo.username=root
#spring.datasource.accessvideo.password=yjh@123!
spring.datasource.accessvideo.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.datasource.accessvideo.publicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL19LiGbPzoLBZJvUqZoxeEeknRpuGc8aeMq9j+I/Jl79mem92wjn7NwrwmYfAziF6IaKZpDaIph64DdrfoesosCAwEAAQ==
spring.datasource.accessvideo.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${spring.datasource.accessvideo.publicKey}
# 下面为连接池的补充设置，应用到上面所有数据源中
spring.datasource.accessvideo.initialSize=5
spring.datasource.accessvideo.minIdle=5
spring.datasource.accessvideo.maxActive=20
# 配置获取连接等待超时的时间
spring.datasource.accessvideo.maxWait=60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
spring.datasource.accessvideo.timeBetweenEvictionRunsMillis=60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
spring.datasource.accessvideo.minEvictableIdleTimeMillis=300000
spring.datasource.accessvideo.validationQuery=SELECT 1 FROM DUAL
spring.datasource.accessvideo.testWhileIdle=true
spring.datasource.accessvideo.testOnBorrow=false
spring.datasource.accessvideo.testOnReturn=false
# druid数据源监控web
spring.datasource.accessvideo.filters=config,wall,log4j,stat
spring.datasource.accessvideo.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.accessvideo.useGlobalDataSourceStat=true
#spring.redis.host=localhost
#spring.redis.port=6379
spring.servlet.multipart.max-file-size=1000Mb
spring.servlet.multipart.max-request-size=1000Mb
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
#common config
#服务所在根路径
service.common.serverPath=/opt/app/1
#
##kafka 配置
#spring.kafka.bootstrap-servers=s-appserver-168:9092
#spring.kafka.consumer.auto-offset-reset=latest
#spring.kafka.consumer.group-id=znv-manager
# Redis数据库索引（默认为0）
spring.redis.database=0
# Redis服务器地址
#spring.redis.host=122.112.250.192
spring.redis.host=192.168.9.40
#spring.redis.host=192.168.30.248
# Redis服务器连接端口
spring.redis.port=6379
# Redis服务器连接密码（默认为空）
spring.redis.password=RXzOTarkaH1+1rwn4T6fvWK05FDshW+8RTquOYDxIvOcmueP+hWDnJtlZI7fRQwyjn+GTdIVlWmnzc+VrR5DhA==
#spring.redis.password=XXTVywwUME6KRwHRh0oNHQ==
# 连接池最大连接数（使用负值表示没有限制）
spring.redis.jedis.pool.max-idle=8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
spring.redis.jedis.pool.max-wait=-1
# 连接池中的最大空闲连接
spring.redis.jedis.pool.max-active=8
# 连接池中的最小空闲连接
spring.redis.jedis.pool.min-idle=0
# 连接超时时间（毫秒）
spring.redis.timeout=0
#用户重置密码的初始密码
user.password=123456
#zipkin 使用
#spring.zipkin.rabbitmq.queue=zipkin
#spring.zipkin.sender.type=rabbit
#spring.zipkin.locator.discovery.enabled=true
#spring.sleuth.sampler.probability=1.0
#spring.rabbitmq.host=10.45.156.238
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=admin
#spring.rabbitmq.password=admin
#spring.zipkin.base-url=http://10.45.156.192:9411
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=ALWAYS
#默认feign的hystrix为关闭状态
feign.hystrix.enabled=true
hystrix.command.default.execution.isolation.strategy=SEMAPHORE
#fegin调用
#请求处理的超时时间
ribbon.ReadTimeout=60000
#请求连接的超时时间
ribbon.ConnectTimeout=60000

user.dir=F:/IotCenter/iot-center-accessvideo

#TC MQ
rmq.host=220.248.75.10
rmq.port=5672
rmq.name=tiecheng
rmq.password=tiecheng
rmq.vhost=/algorithm
rmq.route=iot_exc
rmq.taskquename.robotInfo=robotinfo
rmq.taskquename.robotState=robotstate
rmq.taskquename.taskData=taskdata
rmq.taskquename.taskResult=taskresult
rmq.type1=direct
rmq.type2=fanout
rmq.type3=topic
rmq.type4=headers

nvr.sdk.path=/home/yjh_iot_center/iot-center-accessvideo-1.0.0/config/lib
nvr.log.path=/home/yjh_iot_center/iot-center-accessvideo-1.0.0/sdk_log/
nvr.log.level=3
nvr.capture.result=/home/yjh_iot_center/iot-picture/resultImg
nvr.capture.Preset=/home/yjh_iot_center/iot-picture/presets
#                /usr/bin/ffmpeg -rtsp_transport tcp -i rtsp://admin:Yijiahe123@192.168.33.2:557/Streaming/Channels/101?transportmode=unicast -vcodec copy -fflags nobuffer -analyzeduration 0 -f flv -an rtmp://192.168.9.40:11935/live/123
nvr.rtmp.video=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s@%s:%s/Streaming/Channels/%s0%s?transportmode=unicast -vcodec copy -acodec copy -fflags nobuffer -analyzeduration 0 -f flv rtmp://192.168.9.40/live/%s
nvr.rtmp.back=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s@%s:%s/Streaming/tracks/%s0%s?starttime=%s&endtime=%s -vcodec copy -acodec copy -f flv -r 15 -y rtmp://192.168.9.40/history/%s
robot.light.video=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s@%s:%s/Streaming/Channels/10%s?transportmode=unicast -vcodec copy -fflags nobuffer -an -f flv rtmp://192.168.9.40/live/%s
robot.inferad.video=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s/camera0 -vcodec copy -fflags nobuffer -an -f flv rtmp://192.168.9.40/live/%s
robot.A200.infrared.video=/usr/local/bin/ffmpeg -rtsp_transport tcp -i rtsp://%s:%s/video -vcodec copy -fflags nobuffer -an -f flv rtmp://192.168.9.40/live/%s
nginx.picture.preset=http://192.168.9.40:10086/imgs/presets

#1-高清视频，2-普通视频
realtime.video.definition=1
#1-https，2-http
video.https.enable=1
#srsUrl
srs.stop.url=192.168.9.40

#接入服务器的IP和端口
netty.recognize.port=13668
netty.ai.port=13669
netty.server.url=192.168.9.37
nginx.picture.reflact=http://192.168.9.40:10086/imgs/resultImg
nvr.capture.video=/home/yjh_iot_center/iot-picture/video/
nvr.capture.savePath=http://192.168.9.40:10086/imgs/video/
nvr.capture.hotPic=/home/yjh_iot_center/iot-picture/resultImg/
nvr.capture.hotPicshow=http://192.168.9.40:10086/imgs/resultImg/
nvr.capture.hotFir=/home/yjh_iot_center/iot-picture/infrared/
nvr.capture.hotFirShow=http://192.168.9.40:10086/imgs/infrared/
service.video.Path=http://192.168.9.40:18711/videoIntercom/v1/selectByPrimaryId

#webSocket路径配置
system.webSocket.url=http://192.168.9.40:18701/route/syncWebsocket

spring.interface.api=true

# 智能分析主机相关配置
# 请求图像分析接口
intelligent.algorithm.analysis-url=http://127.0.0.1:18711/picAnalyse
# 请求算法更新接口
intelligent.algorithm.update-url=http://192.168.9.40:20013/algorithmUpdate
# 分析结果反馈ip地址
intelligent.algorithm.result-ip=192.168.9.40
# 分析结果返回端口
intelligent.algorithm.result-port=18715
# 静默监视告警类型识别
intelligent.algorithm.silent-monitor-type=sly_dmyw,yw_gkxfw,yw_nc,gbps,xmbhyc,xmbhzc,kgg_ybh,kgg_ybf,wcaqm,wcgz,gzzc,xy,jyz_pl,byq_hxq,hxq_gjbs,hxq_gjzc,hxq_gjtps,ywzt_yfyc,bj_bpmh,bj_bpps,bj_wkps,bjdsyc,bjzc,bj_sxb,sxb_bjdsyc,sxb_bjdszc,bj
# 18类缺陷类型
intelligent.algorithm.defect-type=sly_dmyw,yw_gkxfw,yw_nc,gbps,xmbhyc,kgg_ybh,kgg_ybf,wcaqm,wcgz,xy,jyz_pl,hxq_gjbs,hxq_gjtps,ywzt_yfyc,bj_bpmh,bj_bpps,bj_wkps,bjdsyc
# 判别类型
intelligent.algorithm.distinguish-type=tx_pb
# 27大类作假数据读取配置文件
conf.file.name=inspectionConf.json

# 算法管理平台ftps配置
manager.server.ftps.flag=1
manager.server.ftps.ip=192.168.9.40
manager.server.ftps.port=10012
manager.server.ftps.username=ftpuser
manager.server.ftps.password=ttasdqwe123
manager.server.ftps.keypw=1
manager.server.ftps.remote.path=南京/雨花台区域/500kV变电站

# 巡视主机ftps配置
intelligent.server.ftps.flag=1
intelligent.server.ftps.ip=192.168.9.40
intelligent.server.ftps.port=10012
intelligent.server.ftps.username=ftpuser
intelligent.server.ftps.password=ttasdqwe123
intelligent.server.ftps.keypw=1
intelligent.server.ftps.remote.path=/home/yjh_iot_center/ftps

# 上级系统ftps配置
up.system.ftps.flag=1
up.system.ftps.ip=192.168.9.40
up.system.ftps.port=10012
up.system.ftps.username=ftpuser
up.system.ftps.password=ttasdqwe123
up.system.ftps.keypw=1
up.system.ftps.remote.path=/home/yjh_iot_center/ftps

#mqtt configinfo
mqtt.host=tcp://192.168.9.40:1883
mqtt.serverClientId=iot
mqtt.user=admin
mqtt.pwd=yjh@123!
mqtt.topic=nodes/java/user/alert/2
mqtt.province_name=江苏
mqtt.city_name=南京
mqtt.station_name=500kV江苏变电站
#本机ip
mqtt.section_ip=192.168.10.151
mqtt.node_id=1997030609
mqtt.volt_level=500

#算法图片识别返回
sequential.picRecBack=http://192.168.9.40:18711/tSequentialConf/v1/sequentialRecBack

# 变电站编码
station.code=01
#1调用原有接口 2调用dlt抓图接口
give.pic=2
