#IP 配置
#本机ip
host.ip=172.24.39.9
protocol=https
#tomcat config
spring.application.name=iot-center-accessvideo
server.port=18715
server.session-timeout=1800
server.tomcat.uri-encoding=utf-8
server.tomcat.max-threads=500
server.servlet.context-path=
server.servlet.path=/
server.tomcat.accessVideo-log-pattern=%t [%a] [%I] [%H-%m] %U %s %T
server.tomcat.accessVideo-log-enabled=true

eureka.instance.lease-renewal-intervalw-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15
eureka.client.registry-fetch-interval-seconds=5
eureka.client.serviceUrl.defaultZone=http://${host.ip}:18710/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health
mybatis.configuration.mapUnderscoreToCamelCase=true
#DB mysql configuration
spring.datasource.accessvideo.driverClassName=com.mysql.jdbc.Driver
spring.datasource.accessvideo.type=com.alibaba.druid.pool.DruidDataSource

spring.datasource.accessvideo.url=jdbc:mysql://${host.ip}:3306/intelligenceelec?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&autoReconnect=true
spring.datasource.accessvideo.username=root
spring.datasource.accessvideo.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.datasource.accessvideo.publicKey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL19LiGbPzoLBZJvUqZoxeEeknRpuGc8aeMq9j+I/Jl79mem92wjn7NwrwmYfAziF6IaKZpDaIph64DdrfoesosCAwEAAQ==
spring.datasource.accessvideo.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500;config.decrypt=true;config.decrypt.key=${spring.datasource.accessvideo.publicKey}
spring.datasource.accessvideo.initialSize=5
spring.datasource.accessvideo.minIdle=5
spring.datasource.accessvideo.maxActive=20
spring.datasource.accessvideo.maxWait=60000
spring.datasource.accessvideo.timeBetweenEvictionRunsMillis=60000
spring.datasource.accessvideo.minEvictableIdleTimeMillis=300000
spring.datasource.accessvideo.validationQuery=SELECT 1 FROM DUAL
spring.datasource.accessvideo.testWhileIdle=true
spring.datasource.accessvideo.testOnBorrow=false
spring.datasource.accessvideo.testOnReturn=false
spring.datasource.accessvideo.filters=config,wall,log4j,stat
spring.datasource.accessvideo.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.accessvideo.useGlobalDataSourceStat=true
spring.servlet.multipart.max-file-size=1000Mb
spring.servlet.multipart.max-request-size=1000Mb
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false
#common config
spring.redis.database=0
spring.redis.host=${host.ip}
spring.redis.port=6379
spring.redis.password=HiJsiNeaQe8dPrdOHIGUIdj/yZkRphe1cZP5kyil1UjvhcXLya2/WzHMyIiJI+tKuJf1DMBaUR95SGz8Hi7NQw==
spring.redis.jedis.pool.max-idle=8
spring.redis.jedis.pool.max-wait=-1
spring.redis.jedis.pool.max-active=8
spring.redis.jedis.pool.min-idle=0
spring.redis.timeout=0